# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a8897726e692a14f58bca1f2527bedd041115067ce0a04b207f743ed0cc6b57b6aec6522755c143fed752ac6923c5e43160eb37df1792ab4805753ec5407ac8

test:
  secret_key_base: 89c1c4624ba7b0dd7562ff55a43c2e8f5bbb47c6393571f170008e29ab5f47c7b482247f5c0564c54c44e2330db6f4aaae85a16157ffde4dfb7b52f5ae5025b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
